language: elixir
elixir:
  - 1.3.4
  - 1.4.2
  - 1.5.2
otp_release:
  - 19.1

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - mix test
notifications:
  recipients:
    - kelostrada@gmail.com
